### ISSUE TITLE
Calling exp$stop() doesn't stop experiment in UI

### ISSUE THREAD

**Issue by dsblank** [comet-ml/cometr#18]
After I run an experiment (comet/r/inst/train-examples/caret-example.R) the UI spinner is still spinning for awhile:

![Screenshot from 2020-05-07 09-04-15](https://user-images.githubusercontent.com/168568/81297839-e0fa5e80-9041-11ea-8a7c-f3e0c8a4a2f1.png)

Running from cometr master.

**Comment by daattali** [comment]
That's not what the stop function is for. There is nothing in the original specs I received about stopping the excitement. The stop function is something I added on my own as a way to end (locally) the current experiment, stop sending the keepalive signal,  and let cometr know that no experiment is active so a new one is allowed to begin.

**Comment by daattali** [comment]
My discussions with @Nimrod007 concluded that stopping an experiment means not sending the keepalive signal anymore, so after 10 seconds plus whatever buffer time comet has the UI should stop showing it

**Comment by daattali** [comment]
Currently stopping an experiment means not sending the keepalive signal anymore, so after 10 seconds (plus whatever buffer time comet has) the UI should stop showing it
