### ISSUE TITLE
Logging confusion matrix from R

### ISSUE THREAD

**Issue by nikdata** [comet-ml/cometr#24]
I'm not sure if this is the right spot for requesting enhancements, so apologies in advance. I was looking for a tutorial/example to see how confusion matrices could be logged and didn't find any. I'd like to request the ability to log confusion matrices (if possible).

**Comment by dsblank** [comment]
This is a fine spot :) 

You can find an example of logging a confusion matrix here:

* https://nbviewer.jupyter.org/github/comet-ml/comet-examples/blob/master/notebooks/Comet-R-nnet.ipynb#Testing-the-Model

And more examples and docs here:

* https://www.comet.ml/docs/r-sdk/getting-started/

**Comment by nikdata** [comment]
Awesome! I should have read that file more closely (I scrolled right through without realizing). Thank you!

I'll go ahead and close this issue.

**Comment by dsblank** [comment]
You're welcome, and no problem! 

BTW, you can also make it so that when you click a cell in the matrix visualization, you will open up an image, url, or show the index of the items mapped to that cell. If you are interested in that level of analysis, let me know and I can provide additional details for constructing the JSON in R.

You can also use the Comet Panels to create your own analysis of logged data as well. For more on that option, see:

* https://www.comet.ml/docs/user-interface/panels/

**Comment by nikdata** [comment]
For me, the default view is good. I ended up writing a function to upload the JSON file. However, since I work with {tidymodels}, the {yardstick} confusion matrix was a bit trickier. The only issue I noticed was that the formatting on the webpage was off for column names.

custom function I wrote (it uses JSON lite):

```
log_confmat <- function(cmat, title) {
  
  # cmat must be a yardstick confusion matrix object
  
  # grab the table part
  cm <- cmat$table
  
  # find maximum value
  max_val <- data.frame(cm) %>%
    group_by(Truth) %>%
    summarize(total = sum(Freq), .groups = 'keep') %>%
    slice(which.max(total)) %>%
    pull(total)
  
  title_txt <- paste0('"',title,'"')
  
  a <- paste0('{"title":',title_txt)
  b <- paste0('"labels":', jsonlite::toJSON(c(colnames(cm))))
  c <- paste0('"matrix":',jsonlite::toJSON(matrix(cm, nrow = dim(cm)[1], ncol = dim(cm)[2])))
  d <- paste0('"rowLabel":','"Prediction"')
  e <- paste0('"columnLabel":','"Truth"')
  f <- paste0('"maxSamplesPerCell":',22)
  g <- paste0('"sampleMatrix":', "[]")
  h <- paste0('"type":','"integer"}')
  
  combo <- paste(a,b,c,d,e,f,g,h, sep = ',')
  
  fp <- file('confusion_matrix.json')
  writeLines(c(combo), fp)
  close(fp)
  
  exp$upload_asset('confusion_matrix.json', type = 'confusion-matrix')
  
}
```

Attached is the output (black boxes are intentional). Perhaps this is a separate issue?
<img width="591" alt="Screen Shot 2020-09-28 at 12 04 05 PM" src="https://user-images.githubusercontent.com/24734983/94463895-4848b480-0183-11eb-97d6-637ec38b1719.png">

**Comment by dsblank** [comment]
Thanks for reporting! I'll look to see what could cause that. If you have an experiment page that you could share with me privately that would be useful, but I understand it may have sensitive info. I'm doug@comet.ml
